tap "kaitat/neovim-nightly"
tap "homebrew/bundle"
tap "homebrew/services"

brew "fish"
brew "tig"
brew "git"
brew "tmux"
brew "lua"
brew "wget"

cask "wezterm"
cask "visual-studio-code"
cask "vivaldi"
cask "arc"
cask "raycast"
cask "karabiner-elements"
cask "docker"

