[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1
hook_add = '''
    let g:deoplete#enable_at_startup = 1
    let g:deoplete#enable_smart_case=1
    inoremap <expr><TAB> pumvisible() ? "\<C-N>" : "\<TAB>"
'''

# coc (lsp)
[[plugins]]
repo = 'neoclide/coc.nvim'
build = './install.sh nightly'
merged = '0'
on_ft = ['javascript', 'javascript.jsx', 'typescript', 'typescript.tsx', 'c', 'cpp']
hook_add = '''
  nnoremap gd <Plug>(coc-definition)
  nnoremap gr <Plug>(coc-references)
  nnoremap cr <Plug>(coc-rename)
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1
on_ft = ['ruby']
hook_add = 'let g:deoplete#enable_at_startup = 1'

# completion ruby
[[plugins]]
repo = 'fishbullet/deoplete-ruby'
on_ft = ['ruby']

[[plugins]]
repo = 'cohama/lexima.vim'
on_i = 1
