[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
    if dein#util#_is_windows()
        let cmd = 'tools\\update-dll-mingw'
    elseif dein#util#_is_cygwin()
        let cmd = 'make -f make_cygwin.mak'
    elseif executable('gmake')
        let cmd = 'gmake'
    else
        let cmd = 'make'
    endif
  let g:dein#plugin.build = cmd
'''

# 検索
[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'

[[plugins]]
repo = 'junegunn/fzf.vim'
hook_add = '''
  source ~/.config/nvim/plugins/fzf.rc.vim
'''

# 初期画面の設定
[[plugins]]
repo = 'mhinz/vim-startify'
hook_add = '''
  source ~/.config/nvim/plugins/vim-startify.rc.vim
'''


#tree
[[plugins]]
repo ="kristijanhusak/defx-git"
hook_add = '''
  let g:defx_git#indicators = {
    \ 'Modified'  : '+',
    \ 'Staged'    : '●',
    \ 'Untracked' : '?',
    \ 'Renamed'   : '➜',
    \ 'Unmerged'  : '═',
    \ 'Deleted'   : 'x',
    \ 'Unknown'   : '?'
    \ }
'''

[[plugins]]
repo = 'Shougo/defx.nvim'
depends = ['defx-icons', 'defx-git']
hook_add = '''
  source ~/.config/nvim/plugins/defx.rc.vim
'''
hook_source = '''
  function! Root(path) abort
    return fnamemodify(a:path, ':t')
  endfunction
  call defx#custom#source('file', {
      \ 'root': 'Root',
      \})
  call defx#custom#column('filename', {
      \ 'directory_icon': '',
      \ 'opened_icon': '',
      \ })
  call defx#custom#column('mark', {
      \ 'readonly_icon': '✗',
      \ 'selected_icon': '✓',
      \ })
  call defx#custom#option('_', {
      \ 'columns': 'indent:git:icons:filename',
      \ 'show_ignored_files': 1,
      \ })
'''

[[plugins]]
repo ="kristijanhusak/defx-icons"


# ステータスバー設定(できていない?)
[[plugins]]
repo = 'vim-airline/vim-airline'
hood_add = '''
 source ~/.config/nvim/plugins/vim-airline.rc.vim
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

# 行番号の隣にgitの更新表示(色を変えたいが変更できず)
[[plugins]]
repo = 'airblade/vim-gitgutter'
 hook_add = '''
  set updatetime=250
  let g:gitgutter_sign_added = '●'
  let g:gitgutter_sign_modified = '●'
  let g:gitgutter_sign_removed = '●'
  let g:gitgutter_sign_modified_removed = "●"
'''
#  autocmd Vimenter,Colorscheme * :hi GitGutterAddLine ctermfg=none ctermbg=17
#  autocmd Vimenter,Colorscheme * :hi GitGutterChangeLine ctermfg=none ctermbg=53
#  autocmd Vimenter,Colorscheme * :hi GitGutterDeleteLine ctermfg=none ctermbg=52
#  autocmd Vimenter,Colorscheme * :hi GitGutterChangeDeleteLine ctermfg=none ctermbg=53

# 色付してくれる
[[plugins]]
repo = 'sheerun/vim-polyglot'

# カッコやら、""で囲ってくれる
[[plugins]]
repo = 'tpope/vim-surround'

# syntax
[[plugins]]
repo = 'taichouchou2/html5.vim'


[[plugins]]
repo = 'hail2u/vim-css3-syntax'

# インデント追加するつもりだった(動いてない)
#[[plugins]]
#repo = 'nathanaelkane/vim-indent-guides'
#hood_add = '''
#  autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd  guibg=red   ctermbg=8
#  autocmd VimEnter,Colorscheme * :hi IndentGuidesEven guibg=green ctermbg=0
#'''

# color theme
[[plugins]]
repo = 'ayu-theme/ayu-vim'
hood_add = '''
source ~/.config/nvim/plugins/ayu-vim.rc.vim
'''

[[plugins]]
repo = 'tomtom/tcomment_vim'
hood_add = '''
  source ~/.config/nvim/plugins/tcomment_vim.rc.vim
'''

# coc (lsp)
[[plugins]]
repo = 'neoclide/coc.nvim'
build = './install.sh nightly'
rev = 'release'
merged = '0'
on_i = 1
# on_ft = ['javascript', 'javascript.jsx', 'typescript', 'typescript.tsx', 'c', 'cpp']
hook_add = '''
  source ~/.config/nvim/plugins/coc.nvim.rc.vim
'''

# vim-fugitive(git連携)
[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
  source ~/.config/nvim/plugins/vim-fugitive.rc.vim
'''
