# 補完
# [[plugins]]
# repo = 'Shougo/deoplete.nvim'
# on_event = 'InsertCharPre'
# hook_add = '''
#   source ~/.config/nvim/plugins/deoplete.rc.vim
# '''
# on_i = 1

[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

[[plugins]]
repo = 'Shougo/neco-vim'

[[plugins]]
repo = 'Shougo/neco-syntax'

[[plugins]]
repo = 'ujihisa/neco-look'

[[plugins]]
repo = 'fishbullet/deoplete-ruby'
on_ft = ['ruby']

# coc (lsp)
[[plugins]]
repo = 'neoclide/coc.nvim'
build = './install.sh nightly'
rev = 'release'
merged = '0'
on_i = 1
# on_ft = ['javascript', 'javascript.jsx', 'typescript', 'typescript.tsx', 'c', 'cpp']
hook_add = '''
  source ~/.config/nvim/plugins/coc.nvim.rc.vim
'''

# 閉じカッコ
[[plugins]]
repo = 'cohama/lexima.vim'
on_i = 1

# emmet
[[plugins]]
repo = 'mattn/emmet-vim'
on_i = 1

# js syntax
[[plugins]]
repo = 'herringtondarkholme/yats.vim'
on_ft = ['javascript', 'javascript.jsx', 'typescript', 'typescript.tsx']

# Rubyのend補完
[[plugins]]
repo = 'tpope/vim-endwise'
on_i = 1
on_ft = ['ruby']
