#[metadata]
#name = "samurai"
#author = "kaito"
#
#[colors]
#foreground = "#212121"
#background = "#eeeeee"
#cursor_bg = "#00a022"
#cursor_border = "#eeeeee"
#cursor_fg = "#f7f7f7"
#selection_bg = "#f27200"
#selection_fg = "#212121"
#
#ansi = ["#f27200","#d70c18","#3ebb67","#f2ab00","#2669d7","#f2ab00","#1bc8c8","#c0c0c0"]
#brights = ["#f27200","#d70c18","#3ebb67","#f2ab00","#2669d7","#f2ab00","#1bc8c8","#c0c0c0"]

# nightfox

[colors]
foreground = "#1d344f"
background = "#eaeaea"
cursor_bg = "#1d344f"
cursor_border = "#1d344f"
cursor_fg = "#eaeaea"
compose_cursor = '#e3786c'
selection_bg = "#ced5de"
selection_fg = "#1d344f"
scrollbar_thumb = "#2e537d"
split = "#dbdbdb"
visual_bell = "#1d344f"
ansi = ["#1d344f", "#b95d76", "#618774", "#ba793e", "#4d688e", "#8e6f98", "#6ca7bd", "#cdd1d5"]
brights = ["#24476f", "#c76882", "#629f81", "#ca884a", "#4e75aa", "#9f75ac", "#74b2c9", "#cfd6dd"]

[colors.tab_bar]
background = "#dbdbdb"
inactive_tab_edge = "#dbdbdb"
inactive_tab_edge_hover = "#dbcece"

[colors.tab_bar.active_tab]
bg_color = "#2e537d"
fg_color = "#eaeaea"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "#dbcece"
fg_color = "#233f5e"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#ced6db"
fg_color = "#1d344f"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab]
bg_color = "#eaeaea"
fg_color = "#233f5e"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab_hover]
bg_color = "#ced6db"
fg_color = "#1d344f"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"
