name: aqua
on:
  push:
    paths:
      - aqua/**
      - .github/workflows/aqua.yaml
  pull_request:
    paths:
      - aqua/
      - .github/workflows/aqua.yaml
jobs:
  aqua:
    strategy:
      matrix:
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    env:
      AQUA_CONFIG: ${{ github.workspace }}/aqua/aqua.yaml
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: switch
        uses: actions/checkout@v4
      - name: isntall aqua tool
        uses: aquaproj/aqua-installer@v3.0.0
        with:
          aqua_version: v2.27.3
          policy_allow: "true"
        env:
          AQUA_LOG_COLOR: always
      - name: aquia install
        run: aqua install
