name: fish
on:
  push:
    paths:
      - fish/**
      - .github/workflows/fish.yml
  pull_request:
    paths:
      - fish/**
      - .github/workflows/fish.yml
jobs:
  fish:
    strategy:
      matrix:
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    env:
      AQUA_CONFIG: aqua/aqua.yaml
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: switch
        uses: actions/checkout@v4
      - name: isntall aqua tool
        uses: aquaproj/aqua-installer@v3.0.2
        with:
          aqua_version: v2.38.0
          policy_allow: "true"
        env:
          AQUA_LOG_COLOR: always
      - name: installw fish
        uses: fish-actions/install-fish@v1.1.0
      - name: link dotfiles
        run: dotfiles link .
      - name: exec fish
        run: sh -c "fish -c exit"
